name: Build Sphinx Documentation
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    container:
    image: python:3.6
    steps:
      - uses: actions/checkout@v2
      - name: Build Sphinx documenaton
        run: |
          cd docs
          apt-get install python3-sphinx
          pip install sphinx_rtd_theme
          make html
      - name: Commit documentation build
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "sphinx documentation build"
          git push
